---
- name: Install k3s agent and join cluster
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['server'][0]]['private_ip'] }}:6443 \
      K3S_TOKEN={{ hostvars[groups['server'][0]]['k3s_node_token'] }} sh -
  args:
    creates: /usr/local/bin/k3s-agent