---
- name: Harden all nodes
  hosts: all
  become: yes
  roles:
    - hardening

- name: Install k3s server
  hosts: server
  become: yes
  roles:
    - k3s-server

- name: Install k3s agents
  hosts: agents
  become: yes
  roles:
    - k3s-agent